### ISSUE TITLE
Plugin caching_sha2_password could not be loaded

### ISSUE THREAD

**Issue by pjfancher** [lukeliasi/database-backups-s3#1]
Hi. Thank you for making this handy little backup service. I tried deploying this on Railway for a Mysql database I have running and ran into this Error in the deploy logs:

`mysqldump: Got error: 1045: "Plugin caching_sha2_password could not be loaded: Error loading shared library /usr/lib/mariadb/plugin/caching_sha2_password.so: No such file or directory" when trying to connect`

The database it is trying to connect to is a Mysql Railway service that is running fine. Some quick googling didn't turn up any obvious answers so I thought I'd ask here. Thanks for the help!

**Comment by DaColcha** [comment]
Did you solve the problem?

**Comment by pjfancher** [comment]
Kind of. I ended up just making my own version of this tool. Couldn't figure out why this one didn't work.

**Comment by matthewspear** [comment]
I solved this by creating a new user on my db just for backup and using the legacy password option.

For MySQL:
```sql
CREATE USER 'backup'@'%' IDENTIFIED WITH mysql_native_password BY 'password';
FLUSH PRIVILEGES;
```

You then likely will need to add privileges to allow it to dump the db:
```sql
GRANT PROCESS, SELECT, LOCK TABLES on *.* TO 'backup'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
```
