### ISSUE TITLE
Version mismatch error

### ISSUE THREAD

**Issue by Jemsukie** [lukeliasi/database-backups-s3#2]
![image](https://github.com/lukeliasi/database-backups-s3/assets/108327043/a009b0a5-de65-4e54-89b4-2a4bc483711a)

**Comment by Jemsukie** [comment]
I tried using this template in Railway, but Railway's Postgres is not compatible with `pg_dump 13`, how do we update the `pg_dump` to 16?

**Comment by lukeliasi** [comment]
Are you running with Docker? In the Dockerfile, it installs `postgresql-client` which should install the latest version (16). A specific version can be defined if needed e.g: `postgresql16-client` if you are not running on Docker you should uninstall your current postgres client and install version 16.
