### ISSUE TITLE
Files not cleaned up

### ISSUE THREAD

**Issue by hloehrmann** [lukeliasi/database-backups-s3#5]
I just was contacted by the railway team as my existing instance of this template was using nearly 1TB of ephemeral storage...

The readme states that _Finally, the dumps are cleaned up on the local file system_ - but when looking at the code the `processBackup()` function ends with _4. Upload to S3_.

So did I miss something here?

**Comment by lukeliasi** [comment]
Fixed: https://github.com/lukeliasi/database-backups-s3/pull/7

**Comment by hloehrmann** [comment]
Hey, I think you only removed the dump file, but the compressed file should also be removed!
