### ISSUE TITLE
mySQL backup not working 

### ISSUE THREAD

**Issue by harpalkawatra** [lukeliasi/database-backups-s3#6]
mysqldump: Got error: 1045: "Plugin caching_sha2_password could not be loaded: Error loading shared library /usr/lib/mariadb/plugin/caching_sha2_password.so: No such file or directory" when trying to connect

I am using backup-s3-template in railways. How ti fix that?

**Comment by lukeliasi** [comment]
This should be fixed: https://github.com/lukeliasi/database-backups-s3/pull/4
